import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  canvasContainer: { flex: 1, width: '100%', height: '100%' },
  heritageArchContainer: {
    width: '100%',
    alignItems: 'center',
    marginBottom: 15,
    marginTop: 5,
  },
  heritageArchShape: {
    borderWidth: 1.5,
    borderTopLeftRadius: 30,
    borderTopRightRadius: 30,
    borderBottomLeftRadius: 12,
    borderBottomRightRadius: 12,
    paddingVertical: 12,
    paddingHorizontal: 25,
    alignItems: 'center',
    width: '100%',
    alignSelf: 'stretch',
    overflow: 'hidden',
    shadowColor: '#D4A373',
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  heritageArchTitleText: {
    fontSize: 16,
    fontWeight: '600',
    textAlign: 'center',
  },
  locationCard: {
    borderRadius: 20,
    marginBottom: 15,
    borderWidth: 1.5,
    borderColor: '#D4A37344',
  },
  locationTitle: {},
  locationNameText: {},
  changeCityBtn: {
    backgroundColor: '#D4A373',
    paddingVertical: 6,
    paddingHorizontal: 12,
    borderRadius: 12,
  },
  changeCityBtnText: {
    color: '#1E1B18',
    fontWeight: 'bold',
    fontSize: 13,
  },
  nextPrayerBanner: {
    backgroundColor: 'rgba(212, 163, 115, 0.18)',
    borderWidth: 1.5,
    borderColor: '#D4A373',
    borderRadius: 20,
    paddingVertical: 14,
    paddingHorizontal: 16,
    alignItems: 'center',
    marginBottom: 18,
  },
  nextPrayerTitleText: {
    fontWeight: 'bold',
    color: '#D4A373',
    textAlign: 'center',
  },
  nextPrayerCountdownText: {
    color: '#E5B279',
    fontWeight: '600',
    marginTop: 4,
    textAlign: 'center',
  },
  silentNoticeText: {
    color: '#C86D51',
    fontWeight: 'bold',
    fontSize: 13,
    marginTop: 6,
    textAlign: 'center',
  },
  trackerBadgeMini: {
    backgroundColor: 'rgba(212,163,115,0.2)',
    paddingHorizontal: 10,
    paddingVertical: 4,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#D4A373AA',
  },
  trackerBadgeMiniText: {
    color: '#D4A373',
    fontWeight: 'bold',
    fontSize: 12,
  },
  checkSquareBtn: {
    width: 24,
    height: 24,
    borderRadius: 6,
    borderWidth: 1.8,
    borderColor: '#D4A373',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
  checkSquareBtnActive: {
    backgroundColor: '#D4A373',
  },
  checkSquareText: {
    color: 'transparent',
    fontSize: 13,
    fontWeight: 'bold',
  },
  checkSquareTextActive: {
    color: '#1E1B18',
  },
  sunriseRow: {
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    gap: 6,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderColor: 'rgba(212,163,115,0.2)',
    borderStyle: 'dashed',
  },
  sunriseText: {
    fontStyle: 'italic',
    fontWeight: '500',
    letterSpacing: 0.2,
  },
  sunnahContainer: {
    marginTop: 18,
    borderRadius: 20,
    padding: 16,
    borderWidth: 1.2,
    borderColor: '#D4A37344',
  },
  sunnahHeaderTitle: {
    fontWeight: 'bold',
    fontSize: 15,
    marginBottom: 12,
    textAlign: 'right',
  },
  sunnahRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 10,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0,0,0,0.6)',
    justifyContent: 'center',
    padding: 20,
  },
  modalContent: {
    padding: 20,
    borderRadius: 22,
    maxHeight: '60%',
    alignItems: 'center',
  },
  modalTitle: {
    fontWeight: 'bold',
    marginBottom: 8,
    textAlign: 'center',
  },
  shareOptionBtn: {
    width: '100%',
    backgroundColor: '#D4A373',
    paddingVertical: 12,
    paddingHorizontal: 15,
    borderRadius: 16,
    alignItems: 'center',
    marginBottom: 10,
  },
  shareOptionBtnText: {
    color: '#1E1B18',
    fontWeight: 'bold',
    fontSize: 15,
  },
  cityOption: {
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: '#D4A37355',
    width: '100%',
  },
  cityOptionText: {
    textAlign: 'right',
  },
  closeModalBtn: {
    marginTop: 5,
    backgroundColor: '#C86D51',
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 12,
    alignItems: 'center',
    width: '100%',
  },
  closeModalBtnText: {
    color: '#FFFFFF',
    fontWeight: 'bold',
  },
  centerScreen: { justifyContent: 'center', alignItems: 'center' },
  header: { padding: 10, alignItems: 'center', marginBottom: 15 },
  headerTitle: { fontWeight: 'bold' },
  mainHeaderCard: { padding: 16, borderRadius: 28, alignItems: 'center', marginBottom: 15, borderWidth: 1.5, borderColor: '#D4A37344' },
  clockText: { fontWeight: 'bold', marginBottom: 5 },
  dateText: { marginBottom: 3 },
  hijriText: { fontWeight: '600' },
  verseCard: { padding: 16, borderRadius: 28, marginBottom: 15, borderWidth: 1.5, borderColor: '#D4A37344' },
  verseBadgeTitle: { fontWeight: 'bold', marginBottom: 8 },
  verseText: { textAlign: 'right' },
  verseRef: { textAlign: 'left', fontWeight: 'bold' },
  verseMeaning: { textAlign: 'right', marginTop: 4 },
  // زر المشاركة: أيقونة بس (بدون كلمة) جوا دائرة ذهبية شفافة
  shareBtnEnhanced: { backgroundColor: 'rgba(212,163,115,0.15)', width: 38, height: 38, borderRadius: 19, borderWidth: 1, borderColor: '#D4A373AA', alignItems: 'center', justifyContent: 'center' },
  tasbeehCard: { padding: 16, borderRadius: 28, alignItems: 'center', marginBottom: 15, borderWidth: 1.5, borderColor: '#D4A37344' },
  tasbeehTitle: { fontWeight: 'bold', marginBottom: 4 },
  tasbeehWords: { marginBottom: 15 },
  tasbeehCircle: { justifyContent: 'center', alignItems: 'center', overflow: 'hidden' },
  // زخرفة بسيطة حوالين دوائر التسبيح الذهبية: حلقة رفيعة متقطعة بلون ذهبي
  // فاتح، شوي أكبر من الدائرة نفسها، بتعطي إحساس "ميدالية" تراثية بدون ما
  // تعقّد التصميم. مستخدمة بكل من دائرة الذكر السريع بالهوم ودائرة السبحة.
  tasbihDecorRing: {
    borderWidth: 1.5,
    borderColor: 'rgba(212, 163, 115, 0.55)',
    borderStyle: 'dashed',
    borderRadius: 999,
    padding: 7,
  },
  tasbeehNumber: { fontWeight: 'bold' },
  tasbeehTapLabel: { marginTop: 2, fontWeight: '600' },
  resetTasbeehBtn: { marginTop: 12 },
  resetTasbeehText: { color: '#C86D51' },
  nameCard: { paddingHorizontal: 14, paddingVertical: 18, borderRadius: 28, alignItems: 'center', marginBottom: 15, borderWidth: 1.5, borderColor: '#D4A37344' },
  nameCardHeader: { fontWeight: 'bold', marginBottom: 5 },
  allahName: { fontWeight: 'bold', marginBottom: 4 },
  allahMeaning: { textAlign: 'center' },
  tapHintText: { fontStyle: 'italic', opacity: 0.8 },
  nameCardFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', width: '100%', marginTop: 2, paddingTop: 4 },
  allNamesLinkText: { color: '#D4A373', fontWeight: 'bold' },
  allahListSubtitle: { textAlign: 'center', marginBottom: 15 },
  allahListItemCard: { borderRadius: 22, marginBottom: 12, borderWidth: 1.5, borderColor: '#D4A37344' },
  allahListItemName: { fontWeight: 'bold', textAlign: 'right', marginBottom: 4 },
  allahListItemMeaning: { textAlign: 'right' },
  gridContainer: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between', marginBottom: 30 },
  gridItem: { width: '48%', padding: 20, borderRadius: 28, alignItems: 'center', marginBottom: 15, borderWidth: 1.5, borderColor: '#D4A37344' },
  gridTitle: { fontWeight: 'bold' },
  menuContainer: { paddingHorizontal: 5 },
  menuCard: { padding: 20, borderRadius: 28, marginBottom: 15, borderWidth: 1.5, borderColor: '#D4A37344' },
  menuTitle: { fontWeight: 'bold', marginBottom: 5 },
  menuSubtitle: {},
  card: { borderRadius: 28, marginBottom: 15, borderWidth: 1.5, borderColor: '#D4A37344' },
  counterBadge: { paddingVertical: 6, paddingHorizontal: 14, borderRadius: 18, alignSelf: 'flex-start' },
  counterText: { fontWeight: 'bold' },
  resetButton: { paddingVertical: 12, paddingHorizontal: 25, borderRadius: 22 },
  resetButtonText: { fontWeight: 'bold' },
  sebhaPresetRow: { flexDirection: 'row', gap: 12, marginBottom: 15 },
  sebhaPresetBtn: { paddingVertical: 8, paddingHorizontal: 18, borderRadius: 14, minWidth: 65, alignItems: 'center' },
  sebhaLabel: { fontWeight: 'bold' },
  bigSebhaCircle: { justifyContent: 'center', alignItems: 'center', overflow: 'hidden' },
  bigSebhaNumber: { fontWeight: 'bold' },
  bigSebhaHint: { marginTop: 4, fontWeight: '600' },
  resetSebhaBtn: { marginTop: 35, paddingVertical: 10, paddingHorizontal: 22, borderRadius: 18 },
  resetSebhaText: { color: '#C86D51', fontWeight: 'bold' },
  prayerCard: { padding: 22, borderRadius: 28, marginBottom: 15, borderWidth: 1.5, borderColor: '#D4A37344' },
  prayerTitle: { fontWeight: 'bold', marginBottom: 12, textAlign: 'center' },
  prayerRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingVertical: 10 },
  prayerName: { fontWeight: 'bold' },
  prayerTime: { fontWeight: 'bold' },
  qiblaContainer: { padding: 22, borderRadius: 28, alignItems: 'center', marginBottom: 20, borderWidth: 1.5, borderColor: '#D4A37344' },
  qiblaHeader: { fontWeight: 'bold', marginBottom: 8 },
  qiblaDesc: { textAlign: 'center', lineHeight: 20 },
  settingRow: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 18, borderRadius: 28, marginBottom: 12, borderWidth: 1.5, borderColor: '#D4A37344' },
  settingRowColumn: { padding: 20, borderRadius: 28, marginBottom: 12, borderWidth: 1.5, borderColor: '#D4A37344' },
  settingLabel: { fontWeight: '600' },
  segmentedButtonsRow: { flexDirection: 'row', justifyContent: 'space-between', gap: 10, marginTop: 4 },
  segmentedBtn: { flex: 1, paddingVertical: 10, borderRadius: 14, alignItems: 'center', justifyContent: 'center' },
  segmentedBtnText: { fontWeight: 'bold', fontSize: 14 },
  fontButtonsRow: { flexDirection: 'row', justifyContent: 'space-around', marginTop: 5 },
  fontBtn: { paddingVertical: 10, paddingHorizontal: 18, borderRadius: 14 },
  activeFontBtn: { borderWidth: 2, borderColor: '#D4A373' },
  fontBtnText: { fontWeight: 'bold' },
  policyText: { lineHeight: 22 },
  
  ornateCompassOuterRing: {
    width: 150,
    height: 150,
    borderRadius: 75,
    borderWidth: 3,
    borderColor: '#D4A373',
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(212, 163, 115, 0.08)',
    marginVertical: 10,
    position: 'relative',
  },
  ornateCompassInnerRing: {
    width: 130,
    height: 130,
    borderRadius: 65,
    borderWidth: 1.5,
    borderColor: 'rgba(212, 163, 115, 0.5)',
    borderStyle: 'dashed',
    justifyContent: 'center',
    alignItems: 'center',
  },
  compassCenterDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#D4A373',
    position: 'absolute',
    zIndex: 2,
  },
  compassNeedleContainer: {
    width: '100%',
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    position: 'absolute',
  },
  compassArrowHead: {
    width: 0,
    height: 0,
    borderLeftWidth: 9,
    borderRightWidth: 9,
    borderBottomWidth: 24,
    borderLeftColor: 'transparent',
    borderRightColor: 'transparent',
    position: 'absolute',
    top: 15,
  },
  compassArrowShaft: {
    width: 3.5,
    height: 50,
    position: 'absolute',
    top: 35,
    borderRadius: 2,
  },
});



export { styles };
